### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by DonnyChen** [WicresoftMBSSE/AX7UTA#1]
Design one tool for AX7 Unit test analysis 

- [ 1] Get failed cases from MBSUSP

- [2 ]  Compare  current build and baseline build 

- [ 3]  Get real failure cases

- [ 4]  Analyze failed cases with baseline bugs  

- [ 5] Analyze failed cases with new bugs

- [ 6]  Generate weekly report

**Comment by lenana** [comment]
这个工具最后得到的应该还是excel吧?

**Comment by DonnyChen** [comment]
展现形式 可以是图表 也可以是excel
